### ISSUE TITLE
Phase 1 - Need a way to run both mobile and desktop tests from the command line

### ISSUE THREAD

**Issue by 20twenty** [FadiRazouk/Project-PWA#10]

**Comment by 20twenty** [comment]
I am only able to run desktop mode. 

How do I run mobile layout tests?

**Comment by FadiRazouk** [comment]
i will add this to README

**Comment by 20twenty** [comment]
Following the instructions in the README, I was able to run the test in both modes.

I will close this issue and open a new issue for a future phase to create a way to set the mode from the command line instead of having to edit the config.
