### ISSUE TITLE
Phase 1 - Home page after debts added - many user actions need to be tested

### ISSUE THREAD

**Issue by 20twenty** [FadiRazouk/Project-PWA#11]
All of the items circled in red user engagement points that do not appear to be interacted with in the existing tests. Each one should be tested to ensure it produces a result that can be verified.

![image](https://user-images.githubusercontent.com/1908939/200091558-82419434-3546-4e76-92d8-154382f2417d.png)

**Comment by 20twenty** [comment]
I see the additional testing being done, but some tests are still missing / incomplete:

- test 'Verify clicking on "view categories" dropdown should show all the categories, ID: 38' should include a screenshot to verify the visuals of the categories
- test 'Verify clicking on "closing tips" button should show reminder, ID: 41' seems to be labeled incorrectly. It appears this test is actually clicking on the articles? The test appears to be incomplete. It should be verifying that clicking on "see all" shows the articles page. It appears to not really be testing anything.

- missing a test for clicking on button "see how much you can save"
- missing test for clicking on the Did You Know "Learn more" button

**Comment by FadiRazouk** [comment]
1. added the screenshot for this
2. Its just miss labelled what it does is clicks on see all and it should take you to articals page
3.  clicking on "see how much you can save" will take us to another tab with another URL, and Cypress do not support that, how do you wish we proceed with this?
4. For the know more i am clicking on the each learn more in testcase #40, would you like me to check the text of each popup ?

**Comment by 20twenty** [comment]
1. verified
2. verified
3. Can you use an approach like this to test it?  https://testersdock.com/cypress-new-window/
4. We do not need to verify the text of each one, however, we should verify that a dialog box appears and 
    - title text length > 0
    - contents text length > 0 
    - dialog box can be closed

**Comment by FadiRazouk** [comment]
3: i did a lot of research the only way i can check is if its an <a> tag with an href where i can remove the target attribute and navigate to that URL, with such implication i am unable to do so, any advise on this?
4: should be solved

**Comment by 20twenty** [comment]
3. ok, thanks for trying. We can ignore this one for now. I will open an issue for a future phase just to keep track of it.
4. looks good
