### ISSUE TITLE
Phase 1 - Debts Page after debts added - many items to be tested

### ISSUE THREAD

**Issue by 20twenty** [FadiRazouk/Project-PWA#12]
Many features on the debts page after debts are added appear to be untested. All the items circled in red should be tested. Additionally, the tests should be using the 7 debts outlined in the requirements document so this page is properly activated.

 - sort feature should be fully tested including custom sort drag and drop actions
 - search feature should be tested

![image](https://user-images.githubusercontent.com/1908939/200092143-4181ca34-c8e9-48a2-9c48-791aae686715.png)

**Comment by 20twenty** [comment]
I see the additional tests, but some still appear to me missing / incomplete

- 'Verify debt page Summary slider, ID: 42' should take a screenshot to validate the 2nd pie chart
- There are 5 "sort by" options, but only 3 appear to be tested
- Missing test for clicking on the main body of the debt and verifying navigation to the debt overview page
- Missing test for clicking on the pencil icon on the debt card will navigate to the debt details page

**Comment by FadiRazouk** [comment]
everything should be covered but one "sort by" option and that is the custom one, as i have not found a way to deal with this drag and drop list

**Comment by 20twenty** [comment]
Looks like everything but drag and drop is tested. I will close this issue and open a new one just to keep track that we will need the drag and drop sort test in a future phase.
