### ISSUE TITLE
Phase 1 - Home and Debts page should be tested with the settings specified in the requirements doc

### ISSUE THREAD

**Issue by 20twenty** [FadiRazouk/Project-PWA#13]
Please use the debts / strategy setup as specified in the requirements doc to test the Home and Debts page. This setup is required to maximize the activation of features within these pages.
https://docs.google.com/document/d/1XUFsc5N9Xs-acVkl2552EZnCww2ZDtt8e8yJa2j9qZE/edit#

![image](https://user-images.githubusercontent.com/1908939/200092661-581210fb-c77f-49cc-bc97-b522ad0d726f.png)

**Comment by 20twenty** [comment]
This issue is still open. There are two issues with the current tests implemented:

1. client.json does not include the "Strategy" settings
2. The Home and Debts page screenshots for "after debt added" should be based on this data set

**Comment by FadiRazouk** [comment]
added the new debt settings you provided to those tests

**Comment by 20twenty** [comment]
looks good. closing as completed.
