### ISSUE TITLE
Phase 1 - The reference screenshots for desktop seem to have a mobile width and are not complete screenshots

### ISSUE THREAD

**Issue by 20twenty** [FadiRazouk/Project-PWA#14]

**Comment by FadiRazouk** [comment]
that is totally my fault 🤦‍♂️ i missed up the default view port, this should be fixed i ran desktop tests on mobile view.
<img width="1028" alt="Screen Shot 2022-11-05 at 12 16 18 PM" src="https://user-images.githubusercontent.com/49675923/200114904-04b9ed26-1152-4c9e-8ddf-340ebedf0bc7.png">

**Comment by 20twenty** [comment]
The reference screenshots have the correct dimensions now.
