### ISSUE TITLE
Phase 1 - Debts page screenshot baseline are wrong / missing

### ISSUE THREAD

**Issue by 20twenty** [FadiRazouk/Project-PWA#16]
1. screenshot "debt-page.cy.ts-debt-page-after-debt-added.png" used to be a screenshot of the debts page, now it is a screenshot of the home page. This should go back to being a screenshot of the debts page after debts are added.

2. Need a screenshot of debts page before debts are added - there used to be a test with screenshot of the debts page before debts are added. This test seems to no longer exist. Can you please bring that test back.

**Comment by FadiRazouk** [comment]
You are right, that was caused by my change when adding the client bucket, before when i used to add a debt manually it always redirects me to debt page, for got to edit this, and i also added one for debt-page-before-adding

**Comment by 20twenty** [comment]
Looks good now
