### ISSUE TITLE
Tests and supporting utilities should be written in typescript

### ISSUE THREAD

**Issue by 20twenty** [FadiRazouk/Project-PWA#3]
Please enable typescript and enhance code to be written in typescript as specified in the original requirements:
```
Additional testing requirements are as follows:
- Should run on modern node, npm, typescript, and cypress installations
```

My apologies if the original requirement was not clear enough. However, it is important that tests be written in typescript so we can take full advantage of modern type checkers and code development environments going forward.

Cypress docs for using typescript here:
https://docs.cypress.io/guides/tooling/typescript-support#Install-TypeScript

Original example repo we provided also shows typescript in action here:
https://github.com/20twenty/Dpp2IntegrationTests

**Comment by FadiRazouk** [comment]
This should be done

**Comment by 20twenty** [comment]
Looks good
