### ISSUE TITLE
All image comparisons are failing

### ISSUE THREAD

**Issue by 20twenty** [FadiRazouk/Project-PWA#5]
There are two main issues:
1. The baseline images in the repo are 2x the resolution of the images that are generated when I run the tests - i.e. baselineimages have a width of 780px, while comparison images are generated with a width of 390px.  
 
> [comparison.tar.gz](https://github.com/FadiRazouk/Project-PWA/files/9844704/comparison.tar.gz) is a file with a few comparison images that got generated for me

2. Some content changes over time - there are two kinds of changing content

   a. Changes in a predictable manner based on the day
      - Home page "Daily Inspirations"
      - Home page Debt-free countdown graphic
      - Track page - content can change when bills become overdue, or the month changes

   b. Changes depend on external factors that are not predictable - I can only think of one such element in the app
      - Home page "Articles" - The app will show new articles here when we publish them on our website. We should only verify that articles are showing up, but ignore what articles they actually are.

 
 > I think 2.a. can be solved by using cy.clock() to set a fixed date for all the tests to run with https://docs.cypress.io/api/commands/clock

**Comment by 20twenty** [comment]
Example diff for issue # 1
![image](https://user-images.githubusercontent.com/1908939/197348664-2055a8fb-5b49-41cb-b3d8-6bffe79d7b88.png)

**Comment by FadiRazouk** [comment]
i think somehow i uploaded wrong baseline but the issue i found with the plugin it self, when the page is long (needs scrolling) and there is a fixed footer like the one we have on the navbar, the baseline becomes wrong as it you will see multi footer, for the artical i fixed the date so we should always see th same artical.

**Comment by 20twenty** [comment]
There are still a few issues here:

1. 2x resolution issue
   - when I run with "npx cypress run", all images have width 780px
   - when I run with "npx cypress open", then run a test in the gui, all images have width 390px
   - We will need to run with both methods, so both methods should produce the same resolution

I can resolve this issue by adding the following to the package.json
```
"cy:run": "cypress run --browser chrome --headless",
```
and then running with:
```
npm run cy:run
```

For the other two issues, I am running with "npx cypress open" to match the resolution of the baseline images. I have attached the difference report from the run. I am running with chrome v106
[Archive.zip](https://github.com/FadiRazouk/Project-PWA/files/9847540/Archive.zip)

2. some baseline images seem to be missing elements 
   - sign-in-p2.cy.ts-sign-up-password-page is missing green check marks
   - sign-in.cy.ts-home-page is missing graphics
   - sign-in.cy.ts-sign-up-page is missing the dove graphic

3. navbar and other bottom of page content is in different locations

**Comment by FadiRazouk** [comment]
for the points 1 and 2 i can confirm all the images on the github are the right resolution and the baseline images are fixed, for point 3 this seems to be the issue with this pugin, to solve this we can switch from testing the whole page to testing elemetns, or we can move to another tool, what do you think ?

**Comment by 20twenty** [comment]
points 1 and 2 are resolved. Remaining item 3 will need some other solution that we can push to a next phase. Closing this issue for now.
