### ISSUE TITLE
Add instructions for demonstrating parallel test run

### ISSUE THREAD

**Issue by 20twenty** [FadiRazouk/Project-PWA#7]
I followed the instructions in the README and was able to run tests locally - both interactively and headless

How do I setup an environment to replicate the parallel test run that you are showing?

**Comment by FadiRazouk** [comment]
for the parallel tests they are triggered on any PR on this repo or any new commit, a cron job can also be added to make it run once a day or so, this is connected to a free Cypress dashboard account for better load balancing and distribution on the machines.

**Comment by 20twenty** [comment]
I would like to be able to run tests in parallel locally. I have done the following and it is fine for me. Can you please verify it works for you as well and add to the repo.

Add this to package.json scripts
```
    "cy:run": "cypress run --browser chrome --headless",
    "cy:parallel": "cypress-parallel -s cy:run -t 4 -d 'cypress/e2e/*.cy.ts'"
```

Execute these commands
```
npm install --save-dev cypress-parallel
npm run cy:parallel
```

**Comment by FadiRazouk** [comment]
should be added

**Comment by 20twenty** [comment]
Looks good
